# Generated by Django 6.0.6 on 2026-06-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='revenue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
